= spring-message-board-demo
Francesco Jo <nimbusob@gmail.com>
// Metadata:
:description: Reseña simple de spring-message-board-demo
:keywords: spring-boot, jpa-hibernate, junit5, spock-groovy, spring-rest-docs, tdd, kotlin, gradle, flutter-examples
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
// Refs:
:app-name: app-main
:app-version: 1.0
:link-jdk: https://openjdk.java.net/
:link-spring: https://spring.io/projects/spring-framework
:link-jpa: https://www.oracle.com/technetwork/java/javaee/tech/persistence-jsp-140049.html
:link-flutter: https://flutter.dev/
:link-detekt: https://arturbosch.github.io/detekt/index.html

[[overview]]
= Resumen

Un proyecto simple, establecido sobre la configuración predeterminada de mi proyecto anterior
https://github.com/FrancescoJo/springboot-multimodule-kotlin[springboot-multimodule-kotlin],
que muestra mis habilidades de programación.

- https://spring.io/projects/spring-framework[Spring boot] como RESTful API backend,
- Práctica de https://en.wikipedia.org/wiki/Test-driven_development[Test-driven-development],
- link:{link-jpa}[Java Persistence API],
- Integración de link:{link-flutter}[Flutter] como web frontend con Spring boot.

[[prerequisites]]
== Prerrequisitos y limitaciones

1. link:{link-jdk}[OpenJDK 13] o superior.
2. link:{link-flutter}[Flutter SDK] para proceso de compilación de frontend.
3. (Opcional, recomendado) https://www.jetbrains.com/idea/[IntelliJ IDEA Ultimate] para depuración.

Probado y compilado en estos 3 SO principales en 2020: Windows, MacOS y Linux.

Debido por compatibilidad inadecuada del plugin Gradle y Kotlin, no se puede operar este proyecto en Eclipse IDE.

[[tech-stacks]]
== Componentes tecnológicos

* Herramienta de compilación:
** https://gradle.org/[Gradle 6.5]

* Idiomas:
** link:{link-jdk}[Java 13] - platform runtime
** https://kotlinlang.org/[Kotlin 1.4] - Prueba unitaria de backend
** http://groovy-lang.org/[Groovy 2.5] - Prueba de integración de backend
** https://dart.dev[Dart 2.10] - web frontend

* Frameworks y tiempo de ejecucións:
** http://undertow.io/[Undertow] - para Web application server
** http://spring.io/projects/spring-boot[Spring boot 2] - framework de applicación
** http://hibernate.org/[Hibernate] - implementación de link:{link-jpa}[JPA] / persistent data
** https://github.com/brettwooldridge/HikariCP[HicariCP] - connection pool de la base de datos
** link:{link-flutter}[Flutter] - web frontend

* Cualidad del código
** https://junit.org/junit5/docs/current/user-guide/[JUnit 5]
** http://spockframework.org/[Spock framework] con http://groovy-lang.org/[Groovy]
** link:{link-detekt}[detekt]
** https://spring.io/projects/spring-restdocs[Spring RESTDocs] con
https://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor] - Documentación automatico

[[building-and-running]]
= Compilación y ejecución

Debe asegurarse de que ambos comandos link:{link-jdk}[Java SDK] y link:{link-flutter}[Flutter SDK] sean accesibles
a través de `PATH`, antes del proceso de compilación.

[[how-to-build]]
== Cómo compilar

[source,shell script]
----
./gradlew clean assemble [-PbuildConfig={local|release}]
----

* `buildConfig` será predeterminado como `local` si se omite la opción.
* Creará un archivo JAR Standalone executable en directorio `app-main/build/outputs`
  después de en finalizada la tarea `assemble`.

[[how-to-run]]
== Cómo ejecutar

Debe poner un archivo `application.yml` antes de ejecutar esta aplicación en directorio raíz de proyecto o
contexto raíz de ejecución. Para ayudar un inicio rápido, hay un archivo `application.yml.sample` en directorio raíz.
Simplemente copie lo y cambie el nombre a `application.yml`, y estará listo para comenzar.

Ejecutar aplicación después de compilación como siguiente:

[subs="attributes,verbatim"]
----
java -jar app-main/build/libs/{app-name}-{app-version}.jar
----

y acceder a localhost y numero de puerto escribido en su archivo `application.yml`.

[[code-quality-measurement]]
= Medición de cualidad del código

[[how-to-tests]]
== Cómo ejecutar prueba unitaria y producir un informe de cobertura

Este proyecto está hecho bajo de la práctica de TDD, por la tanto hay muchos casos de prueba para demostrar
la integridad lógica. Como sabemos, la pruebas de integraciones son *pruebas*, pero ejecutarlas lleva mucho tiempo
en lugar de pruebas unitarias. Por lo tanto, esas dos pruebas están separadas y puede ejecutar ambas siguiendo:

[source,shell script]
----
./gradlew test integrationTest jacocoTestReport
----

para ejecutar pruebas todos y producir el informe de cobertura en cada de `build/reports` directorios.

Hay un buen artículo sobre pruebas - acceso a
https://testing.googleblog.com/2015/04/just-say-no-to-more-end-to-end-tests.html[Google Testing Blog post] para mas detalles.

[[how-to-analyze]]
== Cómo ejecutar análisis estático y producir un informe

Este proyecto utiliza link:{link-detekt}[detekt] como analizador estático.
La tarea `detekt` de Gradle desarrollará un análisis estático siguiendo:

[source,shell script]
----
./gradlew detekt
----
